### ISSUE TITLE
Some of the tests are using `@AroundInvoke` on the target class and should be exluded or changed for Lite

### ISSUE THREAD

**Issue by dstepanov** [jakartaee/cdi-tck#356]
If I'm correct that it's only supported on CDI-full:
- `declaring @AroundInvoke interceptor methods on target classes (i.e. on beans).`

`AroundInvokeOrderTest` is one of the cases, I think it should be changed to validate the order without the bean itself interceptor.

**Comment by manovotn** [comment]
`AroundInvokeOrderTest` is a test from interceptors specification TCK, not a CDI one.
Therefore, there is no notion of Lite and Full.
(all of interceptors TCK are under a separate package)

I think we only changed tests with interceptors within CDI tests and left interceptors TCK as such untouched because those need to cover full spectrum of what interceptors specification requires. There were also several complaints on interceptors TCK being included inside CDI TCK but nobody really came up with anything better.

So I think the only thing we can do now, is adjust interceptors TCK as well and give it categories like we did for other tests.

@dstepanov do you have a more complete list of problematic tests?

**Comment by dstepanov** [comment]
I think it’s a good idea to have that test but maybe it can be adjusted. Can somebody clarify that the scenario with a target interceptor is supported? FYI @graemerocher 

We do have a list of tests that are failing for us but it’s mostly because it’s WIP

**Comment by dstepanov** [comment]
I have implemented this functionality so I guess we can close it.

**Comment by Ladicek** [comment]
I guess we'll get to this again with Quarkus / ArC, where we don't intend to implement interceptors declared on target classes (or at least didn't, last time I checked), so adding groups to the interceptors TCK is still likely to happen. I think :-)
