### ISSUE TITLE
org.jboss.cdi.tck.tests.full.extensions.lifecycle.bbd.broken.passivatingScope.AddingPassivatingScopeTest

### ISSUE THREAD

**Issue by jeanouii** [jakartaee/cdi-tck#431]
Per the current [TCK Process documentation](https://jakarta.ee/committees/specification/tckprocess/), please find bellow a challenge related to CDI TCK. Can someone please add the `challenge` label which is required by the TCK Process but not available to everyone to add.

### The relevant specification version and section number(s)

https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#passivation_validation
https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#exceptions

### The coordinates of the challenged test(s)

Only following test in the class are related to the challenge 

* testAddingScopeType

### The exact TCK version

CDI TCK version 4.0.7

### The implementation being tested, including name and company

Apache OpenWebBeans 4.0.0-SNAPSHOT from the Apache Software Foundation

### A full description of why the test is invalid and what the correct behavior is believed to be

This test add a passivating scope to a non serializable bean. Per validation rules defined in https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#passivation_validation this is not legal and must result in a deployment error.

>  If a managed bean which declares a passivating scope, or a built-in bean:
>
> * is not passivation capable,
> * has an injection point that is not passivation capable,
> * has an interceptor or decorator that is not passivation capable,
> * has an interceptor or decorator with an injection point that is not passivation capable,
>
> then the container automatically detects the problem and treats it as a deployment problem.

From https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#exceptions

> Deployment problems - occur when there are problems resolving dependencies, or inconsistent specialization (in CDI Full), in a particular deployment. If a deployment problem occurs, the container must throw a subclass of jakarta.enterprise.inject.spi.DeploymentException.

The test is asserting the wrong exception jakarta.enterprise.inject.spi.DefinitionException

### Any supporting material; debug logs, test output, test logs, run scripts, etc.

````
org.apache.webbeans.exception.WebBeansDeploymentException: Passivation scoped defined bean must be passivation capable, but bean : RomanEmpire, WebBeansType:MANAGED, Name:null, API Types:[java.lang.Object,org.jboss.cdi.tck.tests.full.extensions.lifecycle.bbd.broken.passivatingScope.RomanEmpire], Qualifiers:[jakarta.enterprise.inject.Default,jakarta.enterprise.inject.Any] is not passivation capable

	at org.apache.webbeans.config.BeansDeployer.checkPassivationScope(BeansDeployer.java:1951)
````

**Comment by manovotn** [comment]
I agree that there is discrepancy between spec and TCK. Other passivation validating tests (from just quickly scanning them) seem to expect `DeploymentException` as per spec.
As a side note, this is also an [issue for Weld](https://issues.redhat.com/browse/WELD-2741) where we've been throwing `DefinitionException` for as long as that code dates back - probably an oversight back from when the test was added.

**Comment by jeanouii** [comment]
Thanks @manovotn 
That's why diversity in implementations is good and benefits the entire industry, including Weld which will gain a bit more consistency.

**Comment by brideck** [comment]
Per the [Jakarta EE TCK Process](https://jakarta.ee/committees/specification/tckprocess/), the fix for this challenge is inappropriate as it (knowingly) breaks an implementation (Weld) that has already passed the TCK.

From the section on Accepted Challenges:
As another alternative to excluding a challenged test, it may be possible to adjust the test validation logic to “expand” the validation check. E.g. if a test expects a value “A1” for a specific variable “x”, but a challenge is raised arguing that the specification language actually allows for either values “A1” and “A2” (but no other values) to be valid values for “x”, then it could be a valid course of action to modify the challenged test to allow either “A1” OR “A2” for “x”.

Since this line of thinking might be applied to cases that aren’t quite as straightforward as this example, care should be taken when using this approach. A particular danger is that an implementation that has already demonstrated compliance before the challenge was raised might actually not pass the new, modified test.

To limit the confusion and additional work such a scenario would cause, if there is already at least one certified compatible implementation before the challenge, the new, modified TCK should be run against at least one such implementation (and ideally all of them) before the changes are published, released, and finalized.

If such a change were released, and it was later found to cause a previously-certified implementation to fail the new, modified test, then excluding the test would likely be the only option, and this would require yet another, additional service release.
