### ISSUE TITLE
Revisit htmlunit usage in CDI TCK

### ISSUE THREAD

**Issue by manovotn** [jakartaee/cdi-tck#441]
According to https://github.com/jakartaee/cdi-tck/issues/434, `htmlunit` is causing issues with newer javascript and at its core uses engine that's been problematic for some time.

For next (major/minor) version, we should look for a replacement that we could rewrite the affected tests with (estimated 20-30 tests?).
We don't mean to change what those tests do, just the tooling we use to make assertions.

One of the options (shown in https://github.com/jakartaee/cdi-tck/pull/437) is Selenium.
We should pick something that provides similar testing capabilities and also allows impls to perform execution with as little hassle as possible.

**Comment by brideck** [comment]
It should be noted that even if a wholesale change in technology isn't made for the 4.1 TCK, the version of HTMLUnit should be upgraded to 3.x to avoid a [CVE](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-26119).

Some changes to test source would be needed in order to [migrate](https://www.htmlunit.org/migration.html) to a 3.x version.

**Comment by edburns** [comment]
Faces also uses HtmlUnit.

**Comment by JanWesterkamp-iJUG** [comment]
Current use of Selenium:

- Jakarta CDI TCK Web Impl (found in 4.0.9)
- Jakarta CDI TCK Distribution (found in 4.0.9, with a transitive depedency to the above)

**Comment by starksm64** [comment]
We will need to move this to the platform tck as an issue against the https://github.com/jakartaee/platform-tck/tree/master/cdi-ee-tck codebase.

https://github.com/jakartaee/platform-tck/issues/1228
